//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkout
    {
        public int id { get; set; }
        public int Address_id { get; set; }
        public int Room_id { get; set; }
    
        public virtual CustomerRegestration CustomerRegestration { get; set; }
        public virtual Room Room { get; set; }
    }
}
